feat: add events when opening/closing a modal
BBVAEngineering/ember-modal-service pull request #130
Opened 2020-10-02 07:08 UTC by josex2r

2020-10-02 07:11 UTC, cmatilla submitted a review, later dismissed

2020-10-02 07:18 UTC, Angel-M-R approved these changes

2020-10-02 07:18 UTC, xe21500 commented on tests/unit/services/modal-test.js
> +			assert.ok(1, 'modal is closed');
I think I would test this a bit different by making the event handler function a sinon spy and just checking `spy.calledWithArguments('foo')`

2020-10-02 07:18 UTC, eumendoza submitted a review, later dismissed

2020-10-02 07:18 UTC, xe21500 submitted a review, later dismissed

2020-10-02 07:23 UTC, adrigzr requested changes

2020-10-02 07:23 UTC, adrigzr commented on addon/services/modal.js
> +		this.trigger('close', key);
This `close` should be trigger for every modal closed (inside `forEach`) with a modal instance/name as argument.

2020-10-05 10:06 UTC, adrigzr approved these changes

2020-10-05 11:05 UTC, merged

2020-10-05 11:17 UTC, adrigzr commented
:tada: This PR is included in version 2.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ember-modal-service/v/2.5.0)
- [GitHub release](https://github.com/BBVAEngineering/ember-modal-service/releases/tag/v2.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: